### ISSUE TITLE
There might be some errors in the Moving-Window Integration

### ISSUE THREAD

**Issue by Ohyoukillkenny** [rafaelmmoreira/PanTompkinsQRS#1]
Thanks for the amazing implementation of PanTompkins Algorithm in C.
However, after running this code on the mitdb, I found the results were not exactly the same as the paper presented, exp., 102.

So I looked into details of your code, and I found something that might be useful.
In panTompkins.c file, from line 314 to line 326:

```c
// Moving-Window Integration
// Implemented as proposed by the original paper.
// y(nT) = (1/N)[x(nT - (N - 1)T) + x(nT - (N - 2)T) + ... x(nT)]
// WINDOWSIZE, in samples, must be defined so that the window is ~150ms.
for (i = 0; i < WINDOWSIZE; i++)
{
	integral[current] = 0;
	if (current >= i)
		integral[current] += integral[current - i];
	else
		break;
}
integral[current] /= i;
```

It seems the `integral[current]` will always be 0, as you initialize the `integral[current]` in the loop as 0.

**Comment by Ohyoukillkenny** [comment]
Moreover, should the `current = 499;` in line 251 be `current = MAXSIZE-1`?

**Comment by rafaelmmoreira** [comment]
> Thanks for the amazing implementation of PanTompkins Algorithm in C.
> However, after running this code on the mitdb, I found the results were not exactly the same as the paper presented, exp., 102.
> 
> So I looked into details of your code, and I found something that might be useful.
> In panTompkins.c file, from line 314 to line 326:
> 
> ```c
> // Moving-Window Integration
> // Implemented as proposed by the original paper.
> // y(nT) = (1/N)[x(nT - (N - 1)T) + x(nT - (N - 2)T) + ... x(nT)]
> // WINDOWSIZE, in samples, must be defined so that the window is ~150ms.
> for (i = 0; i < WINDOWSIZE; i++)
> {
> 	integral[current] = 0;
> 	if (current >= i)
> 		integral[current] += integral[current - i];
> 	else
> 		break;
> }
> integral[current] /= i;
> ```
> 
> It seems the `integral[current]` will always be 0, as you initialize the `integral[current]` in the loop as 0.

Sounds legit. I haven't touched this in a while, but I do recall having some occasional issues with one of the waveforms. I'll check it out as soon as I have some spare time this week. Thanks!!

**Comment by rafaelmmoreira** [comment]
It took me a little longer to get back to work on this project - but hey, technically it's still "this week", right? ;)
Thanks a lot, I think it's fixed! I plotted a few waveforms (original, filtered, derivative, squared derivative, integral and output) using a small segment of the sample input showing the result.

**Comment by Ohyoukillkenny** [comment]
> It took me a little longer to get back to work on this project - but hey, technically it's still "this week", right? ;)
> Thanks a lot, I think it's fixed! I plotted a few waveforms (original, filtered, derivative, squared derivative, integral and output) using a small segment of the sample input showing the result.

Thanks a lot !!!
I think the current implementation is quite awesome, and I have learned a lot about pan tompkins algorithm by reading and duplicating your code.

(a small suggestion: the experiment results of your program under mitbih benchmarking are still not similar to the results proposed by the original paper, maybe you can check it if you have time)

Some other useful resource:
https://www.mathworks.com/matlabcentral/fileexchange/45840-complete-pan-tompkins-implementation-ecg-qrs-detector

**Comment by rafaelmmoreira** [comment]
Hey, thanks for the help! I'm glad it's been useful for someone else!

I guess at last it works fine. When it couldn't find a peak for too long and then found one by looking back a few samples using the lower thresholds it'd output '1' for the current sample rather than the old one.
I added an output buffer that can be modified before actually outputting the answer. 

I guess now it's only a matter of adjusting parameters (such as the integration window size) for each signal you'd like to test. 

If you do catch any other bug, feel free to report it again - it's really helpful!
