### ISSUE TITLE
Output file format

### ISSUE THREAD

**Issue by renatosc** [rafaelmmoreira/PanTompkinsQRS#2]
Hi, I just run your example. Your input file has 650,000 points, but the output generated by the code has only 649,978. How do I align them so I can correctly identify the index of the peaks in the input data?

UPDATE: I noticed that they are already aligned (although my output file starts with a "1" and the input is not starting with a QRS complex). So, except for that misclassification, I can just assume that the index of the output is the same of the input, right?

**Comment by rafaelmmoreira** [comment]
Yes. The filters add a delay to the signal, which causes a mismatch between the original signal and the output. To fix that, I discarded the first few samples.
The algorithm takes about 2 seconds of training to start working correctly as well. Until then, it will give you a few false positives as it adjusts its thresholds. If you're using it as part of a larger system (like heartbeat classification), I'd advise you to force it to run for 2 seconds without feeding its results to the next module. Afterwards it should work well.

**Comment by renatosc** [comment]
Got it. Obrigado.
